---
image: node:alpine
definitions:
  caches:
    npm: ~/.npm
pipelines:
  default:
    - step:
        name: Validate code
        caches:
          - npm
        script:
          - npm ci
          
  branches:
    master:
      - step:
          name: Deploy to Expo
          deployment: production
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD
            - npx expo publish