definitions:
  caches:
    npm: $HOME/.npm
image: node:alpine
pipelines:
  default:
    - step:
        name: Deploy to Expo
        trigger: automatic
        deployment: staging
        caches:
          - npm
        script:
          - npm install
          - npx exp login -u jetobe95 -p Colombia2010
          - npx exp publish --non-interactive